//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMEntities.Models
{
    using System;
    using System.Collections.Generic;

    public partial class EDM_EduPlannerSubjectArea
    {
        public EDM_EduPlannerSubjectArea()
        {
        }
    
        public string subjectareaID { get; set; }
        public string subjectareaLabel { get; set; }
        public int fieldID { get; set; }

        public virtual EDM_EduPlannerField EDM_EduPlannerField { get; set; }
        public virtual ICollection<EDM_EduPlannerNoc> EDM_EduPlannerNocs { get; set; }
    }
}
