//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDM_EduPlannerLength
    {
        public EDM_EduPlannerLength()
        {
            this.EDM_EduPlannerPrograms = new List<EDM_EduPlannerProgram>();
        }
    
        public int lengthID { get; set; }
        public string lengthLabel { get; set; }
    
        public virtual ICollection<EDM_EduPlannerProgram> EDM_EduPlannerPrograms { get; set; }
    }
}
