//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMEntities.Models
{
    using System;
    using System.Collections.Generic;

    public partial class EDM_EduPlannerProgram
    {
        public EDM_EduPlannerProgram()
        {
            this.EDM_EduPlannerLengths = new List<EDM_EduPlannerLength>();
            this.EDM_EduPlannerNoc = new List<EDM_EduPlannerNoc>();
            this.EDM_EduPlannerSubjectAreas = new List<EDM_EduPlannerSubjectArea>();
        }

        public int programID { get; set; }
        public string programAdvice { get; set; }
        public string programADA { get; set; }
        public string programContact { get; set; }
        public string programLength { get; set; }
        public string programLocation { get; set; }
        public string programName { get; set; }
        public string programUrl { get; set; }
        public Nullable<int> ttcProgramID { get; set; }
        public string trainingLevel { get; set; }
        public string trainingLocation { get; set; }
        public string credentialLabel { get; set; }
        public string admFeedADA { get; set; }
        public string admFeedApply { get; set; }
        public string admFeedApproval { get; set; }
        public string admFeedMyComm { get; set; }
        public string admFeedNotes { get; set; }
        public string admFeedProvExams { get; set; }
        public string admFeedRequirements { get; set; }
        public string admFeedStartDate { get; set; }
        public string admFeedTechEntry { get; set; }
        public string admPAR { get; set; }
        public string eboExProv { get; set; }
        public string eboIIB { get; set; }
        public string eboIntraInstitution { get; set; }
        public string feeApplication { get; set; }
        public string feeBooks { get; set; }
        public string feeTuition { get; set; }
        public string institutionLabel { get; set; }
        public Nullable<bool> isAboriginal { get; set; }
        public Nullable<bool> isApprenticeship { get; set; }
        public Nullable<bool> isCoop { get; set; }
        public Nullable<bool> isDevelopmental { get; set; }
        public Nullable<bool> isEpprentice { get; set; }
        public Nullable<bool> isGraduate { get; set; }
        public Nullable<bool> isPreApprenticeship { get; set; }
        public Nullable<bool> isRedSeal { get; set; }
        public Nullable<bool> isWorkExperience { get; set; }
    
        public virtual ICollection<EDM_EduPlannerLength> EDM_EduPlannerLengths { get; set; }
        public virtual ICollection<EDM_EduPlannerNoc> EDM_EduPlannerNoc { get; set; }
        public virtual ICollection<EDM_EduPlannerSubjectArea> EDM_EduPlannerSubjectAreas { get; set; }
    }
}
