//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDM_EduPlannerNoc
    {
        public EDM_EduPlannerNoc()
        {
            this.EDM_EduPlannerSubjectAreas = new List<EDM_EduPlannerSubjectArea>();
        }
        
        public string noc { get; set; }
        public string nocLabel { get; set; }

        public virtual ICollection<EDM_EduPlannerSubjectArea> EDM_EduPlannerSubjectAreas { get; set; }
    }
}
